### ISSUE TITLE
Running infinite loop, unexpected results

### ISSUE THREAD

**Issue by Garux** [leomccormack/convhull_3d#1]
At first, thanks for this simple drop in library.
Works well mostly, but some edge (not very) cases were found.
Sometimes it randomly runs into long or even infinite loop; likely in case of odd points, located precisely on resulting faces
 \+ using 30-50Mb of memory during this with just a handful of points.
It's simply reproducible with such geometry:
![11](https://user-images.githubusercontent.com/1734117/48149777-e5ab4e80-e2b4-11e8-8848-e1bd889d021e.png)
(merging its vertices)
<details> 
  <summary>Which are: </summary>
(-744 3300 7552)
(-808 3300 7552)
(-808 3364 7552)
(-744 3364 7552)
(-744 3364 7551)
(-808 3364 7551)
(-744 3300 7551)
(-808 3300 7551)
(-1000 3300 7552)
(-1064 3300 7552)
(-1064 3364 7552)
(-1000 3364 7552)
(-1000 3364 7551)
(-1064 3364 7551)
(-1000 3300 7551)
(-1064 3300 7551)
(-872 3300 7552)
(-936 3300 7552)
(-936 3364 7552)
(-872 3364 7552)
(-872 3364 7551)
(-936 3364 7551)
(-872 3300 7551)
(-936 3300 7551)
(-744 3428 7552)
(-808 3428 7552)
(-808 3492 7552)
(-744 3492 7552)
(-744 3492 7551)
(-808 3492 7551)
(-744 3428 7551)
(-808 3428 7551)
(-744 3556 7552)
(-808 3556 7552)
(-808 3620 7552)
(-744 3620 7552)
(-744 3620 7551)
(-808 3620 7551)
(-744 3556 7551)
(-808 3556 7551)
(-1000 3428 7552)
(-1064 3428 7552)
(-1064 3492 7552)
(-1000 3492 7552)
(-1000 3492 7551)
(-1064 3492 7551)
(-1000 3428 7551)
(-1064 3428 7551)
(-872 3428 7552)
(-936 3428 7552)
(-936 3492 7552)
(-872 3492 7552)
(-872 3492 7551)
(-936 3492 7551)
(-872 3428 7551)
(-936 3428 7551)
(-1000 3556 7552)
(-1064 3556 7552)
(-1064 3620 7552)
(-1000 3620 7552)
(-1000 3620 7551)
(-1064 3620 7551)
(-1000 3556 7551)
(-1064 3556 7551)
(-872 3556 7552)
(-936 3556 7552)
(-936 3620 7552)
(-872 3620 7552)
(-872 3620 7551)
(-936 3620 7551)
(-872 3556 7551)
(-936 3556 7551)
</details>

Noticeable things are:
+ axially aligned planes
+ points are on integer grid (same rotated geometry runs well)
+ it's height is just 1unit (using ~100 makes things better) (likely volume proportions matter)
+ bug hardening after moving objects to greater coordinates

Further playing around also has shown consistency issue:
this:
![22](https://user-images.githubusercontent.com/1734117/48151487-4f2d5c00-e2b9-11e8-9458-6dad81850e3e.png)
<details> 
  <summary>(points) </summary>
(-7671.07 -3235.66 1350.5)
(-7966.3 -3165.18 1528.24)
(-7860.47 -3017.46 1558.03)
(-7565.25 -3087.95 1380.28)
(-7565.25 -3089.2 1375.66)
(-7860.47 -3018.71 1553.41)
(-7671.07 -3236.91 1345.87)
(-7966.3 -3166.43 1523.62)
(-7333.67 -3316.21 1067.36)
(-7628.9 -3245.73 1245.1)
(-7523.07 -3098.02 1274.89)
(-7227.85 -3168.5 1097.15)
(-7227.85 -3169.75 1092.52)
(-7523.07 -3099.26 1270.27)
(-7333.67 -3317.46 1062.74)
(-7628.9 -3246.98 1240.48)
</details>

randomly turns into this:
![33](https://user-images.githubusercontent.com/1734117/48151558-7552fc00-e2b9-11e8-8983-3e9708b6dff8.png)
while should be this:
![44](https://user-images.githubusercontent.com/1734117/48151586-8ac82600-e2b9-11e8-9f15-c0aa8af91585.png)

Same happens with the first example (losing one or more of vertices), but infinite loop is more probable.

### Use specs
+ compiling as c++ with gcc under win32 and win64
+ precision is double; using float makes named issues to happen way more often; using long double haven't improved the state
+ CBLAS is not used
Trying to tune noise value just shown, that current value is well ballancing in between of these two issues.

**Comment by leomccormack** [comment]
Hi! Thanks for letting me know. Would you be willing to share the problematic obj files? (leo.mccormack(at)aalto.fi)

**Comment by Garux** [comment]
Hi, i'v got no obj files, but provided problematic point clouds in the first post.

**Comment by leomccormack** [comment]
Hi, apologies for the delay!

With the latest commit, you should instead hit an assertion error with details on how to resolve the issue : )
