### ISSUE TITLE
Co-linear points cause erratic behavior

### ISSUE THREAD

**Issue by NateAM** [leomccormack/convhull_3d#2]
I have a case where sometimes my incoming points (~1000 points) are on a regularly spaced grid. When this happens the plane_3d function in the main loop of convhull_3d_build (in sub-loop with the comment:  "Add faces connecting horizon to the new point") can return wildly varying values for cfi and dfi.

This appears to propagate (probably because I have so many colinear points) and eventually causes the program to fail. This failure is intermittent since, strangely, I can do:

    std::vector< ch_vertex > vertices;
    int *faceIndices= NULL;
    int nFaces;
    ...
    convhull_3d_build( &vertices[0], vertices.size(), &faceIndices, &nFaces); //Succeeds
    convhull_3d_build( &vertices[0], vertices.size(), &faceIndices, &nFaces); //Fails
    convhull_3d_build( &vertices[0], vertices.size(), &faceIndices, &nFaces); //Succeeds
    ...

So it's possible that something stranger is going on. This fail, succeed, fail, pattern continues even if I free faceIndices between each run.

EDIT:

Additionally, I can shake up the pattern by running

    std::vector< ch_vertex > easy_vertices;
    std::vector< ch_vertex > vertices;
    int *faceIndices= NULL;
    int nFaces;
    ...
    convhull_3d_build(&easy_vertices[0], easy_vertices.size(), &faceIndices, &nFaces); //Succeeds
    convhull_3d_build( &vertices[0], vertices.size(), &faceIndices, &nFaces); //Fails
    convhull_3d_build( &vertices[0], vertices.size(), &faceIndices, &nFaces); //Succeeds
    convhull_3d_build( &vertices[0], vertices.size(), &faceIndices, &nFaces); //Fails
    ...

where `easy_vertices` is some collection of points without any co-linear points.

**Comment by leomccormack** [comment]
Apologies for the delay! With the latest commit, some previous issues have been fixed: ). 
Also some extra assertion checks are there, which should help narrow things down for the other known issues.
